version: 2.1

jobs:
  build:
    docker:
      - image: ryangraham/credz:0.0.5
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: ./build/credz --test 
      - run:
          name: Run
          command: ./build/credz --version
