version: 2.1

jobs:
  build:
    docker:
      - image: ryangraham/credz:0.0.1
    steps:
      - checkout
      - run:
          name: Install boost
          command: sudo apt update && sudo apt install -y libboost-all-dev
      - run:
          name: Build
          command: make build
      - run:
          name: Run
          command: ./build/credz --version
