version: 2.1

jobs:
  build_linux:
    docker:
      - image: ryangraham/credz:0.0.7
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: ./build/credz --test 
      - run:
          name: Run
          command: ./build/credz --version

  build_mac:
    macos:
      xcode: "11.3.1"
    steps:
      - checkout
      # - run:
      #     name: brew update
      #     command: brew update
      - run:
          name: Install cmake
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake
      - run:
          name: Install boost
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install boost
      - run:
          name: Install aws-sdk-cpp
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install aws-sdk-cpp
      - run:
          name: Install cfg
          command: >
            HOMEBREW_NO_AUTO_UPDATE=1 brew tap ryangraham/cfg &&
            HOMEBREW_NO_AUTO_UPDATE=1 brew install cfg
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: ./build/credz --test

workflows:
  version: 2
  build:
    jobs:
      - "build_linux"
      - "build_mac"
