version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Install build tools
          command: sudo apt update && sudo apt install -y build-essential cmake g++
      - run:
          name: Build
          command: make build
      - run:
          name: Run
          command: ./build/credz --version
