version: 2.1

jobs:
  build_linux:
    docker:
      - image: ryangraham/credz:0.0.7
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: ./build/credz --test 
      - run:
          name: Run
          command: ./build/credz --version

  build_mac:
    macos:
      xcode: "11.1.0"
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: ./build/credz --test

workflows:
  version: 2
  build:
    jobs:
      - "build_linux"
      - "build_mac"
